<?php

use Illuminate\Database\Seeder;
use sis5cs\Nacionalidad;

class NacionalidadTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      Nacionalidad::create([
        'id_nacionalidad'=>4,
        'nacionalidad'=>'AFGANISTAN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>8,
        'nacionalidad'=>'ALBANIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>12,
        'nacionalidad'=>'ARGELIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>16,
        'nacionalidad'=>'SAMOA AMERICANA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>20,
        'nacionalidad'=>'ANDORRA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>24,
        'nacionalidad'=>'ANGOLA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>28,
        'nacionalidad'=>'ANTIGUA AND BARBUDA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>31,
        'nacionalidad'=>'AZERBAIYAN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>32,
        'nacionalidad'=>'ARGENTINA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>36,
        'nacionalidad'=>'AUSTRALIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>40,
        'nacionalidad'=>'AUSTRIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>44,
        'nacionalidad'=>'LAS BAHAMAS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>48,
        'nacionalidad'=>'BAREIN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>50,
        'nacionalidad'=>'BANGLADES',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>51,
        'nacionalidad'=>'ARMENIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>52,
        'nacionalidad'=>'BARBADOS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>56,
        'nacionalidad'=>'BELGICA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>60,
        'nacionalidad'=>'BERMUDAS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>64,
        'nacionalidad'=>'BUTAN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>68,
        'nacionalidad'=>'BOLIVIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>70,
        'nacionalidad'=>'BOSNIA Y HERZEGOVINA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>72,
        'nacionalidad'=>'BOTSUANA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>74,
        'nacionalidad'=>'ISLA BOUVET',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>76,
        'nacionalidad'=>'BRASIL',
        'estado'=>true
      ]);

      Nacionalidad::create([
        'id_nacionalidad'=>84,
        'nacionalidad'=>'BELICE',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>86,
        'nacionalidad'=>'TERRITORIO BRITANICO DEL OCEANO INDICO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>90,
        'nacionalidad'=>'ISLA SALOMON',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>92,
        'nacionalidad'=>'ISLAS VIRGENES BRITANICAS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>96,
        'nacionalidad'=>'BRUNEL',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>100,
        'nacionalidad'=>'BULGARIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>104,
        'nacionalidad'=>'BIRMANIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>108,
        'nacionalidad'=>'BURUNDI',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>112,
        'nacionalidad'=>'BIELORRUSIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>116,
        'nacionalidad'=>'CAMBOYA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>120,
        'nacionalidad'=>'CAMERUN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>124,
        'nacionalidad'=>'CANADA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>132,
        'nacionalidad'=>'CABO VERDE',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>136,
        'nacionalidad'=>'ISLAS CAIMAN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>140,
        'nacionalidad'=>'REPUBLICA CENTROAFRICANA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>144,
        'nacionalidad'=>'SRI LANKA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>148,
        'nacionalidad'=>'CHAD',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>152,
        'nacionalidad'=>'CHILE',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>156,
        'nacionalidad'=>'CHINA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>158,
        'nacionalidad'=>'TAIWAN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>162,
        'nacionalidad'=>'ISLA DE NAVIDAD',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>166,
        'nacionalidad'=>'ISLA COCOS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>170,
        'nacionalidad'=>'COLOMBIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>174,
        'nacionalidad'=>'COMORAS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>175,
        'nacionalidad'=>'MAYOTTE',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>178,
        'nacionalidad'=>'REPUBLICA DEL CONGO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>180,
        'nacionalidad'=>'REPUBLICA DEMOCRATICA DEL CONGO ',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>184,
        'nacionalidad'=>'ISLAS COOK',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>188,
        'nacionalidad'=>'COSTA RICA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>191,
        'nacionalidad'=>'CROACIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>192,
        'nacionalidad'=>'CUBA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>196,
        'nacionalidad'=>'CHIPRE',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>203,
        'nacionalidad'=>'REPUBLICA CHECA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>208,
        'nacionalidad'=>'DINAMARCA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>212,
        'nacionalidad'=>'DOMINICA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>214,
        'nacionalidad'=>'REPUBLICA DOMINICANA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>218,
        'nacionalidad'=>'ECUADOR',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>222,
        'nacionalidad'=>'EL SALVADOR',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>226,
        'nacionalidad'=>'GUINEA ECUATORIAL',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>231,
        'nacionalidad'=>'ETIOPIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>232,
        'nacionalidad'=>'ERITREA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>233,
        'nacionalidad'=>'ESTONIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>234,
        'nacionalidad'=>'ISLAS FEROE',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>238,
        'nacionalidad'=>'ISLAS MALVINAS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>239,
        'nacionalidad'=>'OSLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>242,
        'nacionalidad'=>'FIYI',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>246,
        'nacionalidad'=>'FINLADIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>248,
        'nacionalidad'=>'ALAND',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>250,
        'nacionalidad'=>'FRANCIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>254,
        'nacionalidad'=>'GUAYANA FRANCESA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>258,
        'nacionalidad'=>'POLINESIA FRANCESA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>260,
        'nacionalidad'=>'TERRITORIOS AUSTRALES FRANCESES',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>262,
        'nacionalidad'=>'YIBUTI',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>266,
        'nacionalidad'=>'GABON ',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>268,
        'nacionalidad'=>'GEORGIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>270,
        'nacionalidad'=>'GAMBIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>275,
        'nacionalidad'=>'ESTADO DE PALESTINA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>276,
        'nacionalidad'=>'ALEMANIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>288,
        'nacionalidad'=>'GHANA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>292,
        'nacionalidad'=>'GIBRALTAR',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>296,
        'nacionalidad'=>'KIRIBATI',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>300,
        'nacionalidad'=>'GRECIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>304,
        'nacionalidad'=>'GROENLANDIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>308,
        'nacionalidad'=>'GRANADA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>312,
        'nacionalidad'=>'GUADALUPE',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>316,
        'nacionalidad'=>'GUAM',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>320,
        'nacionalidad'=>'GUATEMALA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>324,
        'nacionalidad'=>'GUINEA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>328,
        'nacionalidad'=>'GUYANA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>332,
        'nacionalidad'=>'HAITI',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>334,
        'nacionalidad'=>'AUSTRALIA ISLAS HEARD Y MCDONALD',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>336,
        'nacionalidad'=>'CIUDAD DEL VATICANO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>340,
        'nacionalidad'=>'HONDURAS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>344,
        'nacionalidad'=>'HONG KONG',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>348,
        'nacionalidad'=>'HUNGRIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>352,
        'nacionalidad'=>'ISLANDIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>356,
        'nacionalidad'=>'INDIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>360,
        'nacionalidad'=>'INDONESIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>364,
        'nacionalidad'=>'IRAN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>372,
        'nacionalidad'=>'IRLANDA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>376,
        'nacionalidad'=>'ISRAEL',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>380,
        'nacionalidad'=>'ITALIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>384,
        'nacionalidad'=>'COSTA DE MARFIL',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>388,
        'nacionalidad'=>'JAMAICA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>392,
        'nacionalidad'=>'JAPON',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>398,
        'nacionalidad'=>'KAZAJISTAN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>400,
        'nacionalidad'=>'JORDANIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>404,
        'nacionalidad'=>'KENIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>408,
        'nacionalidad'=>'COREA DEL NORTE',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>410,
        'nacionalidad'=>'COREA DEL SUR',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>414,
        'nacionalidad'=>'KUWAIT',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>417,
        'nacionalidad'=>'KIRGUISTAN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>418,
        'nacionalidad'=>'LAOS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>422,
        'nacionalidad'=>'LIBANO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>426,
        'nacionalidad'=>'LESOTO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>428,
        'nacionalidad'=>'LETONIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>430,
        'nacionalidad'=>'LIBERIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>434,
        'nacionalidad'=>'LIBIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>438,
        'nacionalidad'=>'LIECHTENSTEIN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>440,
        'nacionalidad'=>'LITUANIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>442,
        'nacionalidad'=>'LUXEMBURGO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>446,
        'nacionalidad'=>'MACAO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>450,
        'nacionalidad'=>'MADAGASCAR',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>454,
        'nacionalidad'=>'MALAUI',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>458,
        'nacionalidad'=>'MALASIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>462,
        'nacionalidad'=>'MALDIVAS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>466,
        'nacionalidad'=>'MALI',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>470,
        'nacionalidad'=>'MALTA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>474,
        'nacionalidad'=>'MARTINICA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>478,
        'nacionalidad'=>'MAURITANIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>480,
        'nacionalidad'=>'MAURICIO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>484,
        'nacionalidad'=>'MEXICO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>492,
        'nacionalidad'=>'MONACO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>496,
        'nacionalidad'=>'MONGOLIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>498,
        'nacionalidad'=>'MOLDAVIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>499,
        'nacionalidad'=>'MONTENEGRO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>500,
        'nacionalidad'=>'MONTSERRAT',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>504,
        'nacionalidad'=>'MARRUECOS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>508,
        'nacionalidad'=>'MOZAMBIQUE ',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>512,
        'nacionalidad'=>'OMAN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>516,
        'nacionalidad'=>'NAMIBIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>520,
        'nacionalidad'=>'NAURU',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>524,
        'nacionalidad'=>'NEPAL',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>528,
        'nacionalidad'=>'PAISES BAJOS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>530,
        'nacionalidad'=>'ANTILLAS NEERLANDESAS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>531,
        'nacionalidad'=>'CURAZAO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>533,
        'nacionalidad'=>'ARUBA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>540,
        'nacionalidad'=>'NUEVA CALEDONIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>548,
        'nacionalidad'=>'VANUATU',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>554,
        'nacionalidad'=>'NUEVA ZELANDA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>558,
        'nacionalidad'=>'NICARAGUA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>566,
        'nacionalidad'=>'NIGERIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>570,
        'nacionalidad'=>'NIUE',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>574,
        'nacionalidad'=>'NORFOLK',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>578,
        'nacionalidad'=>'NORUEGA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>580,
        'nacionalidad'=>'ISLAS MARIANAS DEL NORTE',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>583,
        'nacionalidad'=>'MICRONESIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>584,
        'nacionalidad'=>'ISLAS MARSHALL',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>585,
        'nacionalidad'=>'PALAOS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>586,
        'nacionalidad'=>'OAKISTAN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>591,
        'nacionalidad'=>'PANAMA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>598,
        'nacionalidad'=>'PAPUA NUEVA GUINEA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>600,
        'nacionalidad'=>'PARAGUAY',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>604,
        'nacionalidad'=>'PERU',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>608,
        'nacionalidad'=>'FILIPINAS',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>612,
        'nacionalidad'=>'ISLAS PITCAIRN',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>616,
        'nacionalidad'=>'POLONIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>620,
        'nacionalidad'=>'PORTUGAL',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>624,
        'nacionalidad'=>'GUINEA-BISAU',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>626,
        'nacionalidad'=>'TIMOR ORIENTAL',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>630,
        'nacionalidad'=>'PUERTO RICO',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>634,
        'nacionalidad'=>'CATAR',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>638,
        'nacionalidad'=>'REUNION',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>642,
        'nacionalidad'=>'RUMANIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>643,
        'nacionalidad'=>'RUSIA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>646,
        'nacionalidad'=>'RUANDA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>652,
        'nacionalidad'=>'SAN BARTOLOME',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>654,
        'nacionalidad'=>'SAN BARTOLOME',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>659,
        'nacionalidad'=>'SAN CRISTOBAL Y NIEVES',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>660,
        'nacionalidad'=>'ANGUILA',
        'estado'=>true
      ]);
      Nacionalidad::create([
        'id_nacionalidad'=>662,
        'nacionalidad'=>'LUXEMBURGO',
        'estado'=>true
      ]);
    }
  }
